name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the version of Node.js required for your project

    - name: Install dependencies
      run: npm install

    - name: Build the Vue app
      run: npm run build

    - name: Deploy to S3
      uses: pokemon-vue/s3-sync-action@main
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' # e.g., us-east-1
        source: 'dist/' # Built Vue.js files
        destination: 's3://poke-test-v'
        delete: true # Optional: delete files in the bucket not present in the dist folder
